#!/bin/bash

mk_config="config.mk"
mk_file="$CUTILS_PATH/template.mk"
deps=()

function new() {
    if [ -f $mk_config ]; then
        echo "$mk_config exists!" >&2
        exit 1
    fi

    if [ "$1" == "" ]; then
        echo "cmk new <Target>"
        echo "<Target>: xx, libxx.a or libxx.so"
        exit 2
    fi

    echo "Target = $1" >> $mk_config
    echo "Source = \$(wildcard src/*.cpp src/*.c)" >> $mk_config
    echo "Test = \$(wildcard test/*.cpp test/*.c)" >> $mk_config
    echo "Lib =" >> $mk_config
    echo "LibPath =" >> $mk_config
    echo "Include =" >> $mk_config
    echo "Define =" >> $mk_config
    echo "CFLAGS = -g -D_DEBUG -Wall" >> $mk_config
    echo "CXXFLAGS = -std=c++14" >> $mk_config
    echo "LDFLAGS =" >> $mk_config
    echo "Rpath =" >> $mk_config
}

function mk() {
    if [ -d "vendor" ]; then
        VendorPath=vendor
    fi

    Import=${deps[@]} VendorPath=$VendorPath CWORK_PATH=$CWORK_PATH CMK_CONFIG=$mk_config make -f $mk_file $@
}

function all() {
    deps=($(cdep list))
    mk $@
    mk test $@

    # for runtime load
    for pkg in ${deps[@]}; do
        if [ -d "vendor/$pkg/lib" ]; then
            cp vendor/$pkg/lib/*.so lib 2>/dev/null
            continue
        fi

        if [ -d "$CWORK_PATH/$pkg/lib" ]; then
            cp $CWORK_PATH/$pkg/lib/*.so lib 2>/dev/null
        fi
    done
}

function vendor() {
    rm -rf vendor/*

    deps=($(cdep ensure))
    for pkg in ${deps[@]}; do
        (
            cget $pkg
            cd $CWORK_PATH/$pkg
            cmk $@
        )
        if [ -d "$CWORK_PATH/$pkg/include" ]; then
            mkdir -p vendor/$pkg/include
            cp $CWORK_PATH/$pkg/include/*.h vendor/$pkg/include
        fi

        if [ -d "$CWORK_PATH/$pkg/lib" ]; then
            mkdir -p vendor/$pkg/lib
            cp $CWORK_PATH/$pkg/lib/* vendor/$pkg/lib
        fi
    done
}

if [ "$CUTILS_PATH" == "" ]; then
    echo "env.CUTILS_PATH not set!" >&2
    exit 1
fi

if [ "$CWORK_PATH" == "" ]; then
    CWORK_PATH=`echo ~`/cwork
fi

case $1 in
    new)
        $@
    ;;
    all)
        $@
    ;;
    vendor)
        $@
    ;;
    clean)
        make -f $mk_file clean
    ;;
    help)
        echo "Usage: cmk [new|all|vendor|clean]"
    ;;
    *)
        deps=($(cdep list))
        mk $@
    ;;
esac
