#!/bin/bash

function create_mk() {
    if [ -f $1 ]; then
        return
    fi

    echo "create_mk $1 $2"

    echo "Target = $2" >> $1
    echo "Source = \$(wildcard *.cpp *.c)" >> $1
    echo "Lib =" >> $1
    echo "LibPath =" >> $1
    echo "Include =" >> $1
    echo "Define =" >> $1
    echo "CFLAGS = -g -D_DEBUG -Wall" >> $1
    echo "CXXFLAGS = -std=c++14" >> $1
    echo "LDFLAGS =" >> $1
    echo "Rpath =" >> $1
    echo "" >> $1
    echo "include \$(CUTILS_PATH)/template.cmk" >> $1
}

if [ "$CUTILS_PATH" == "" ]; then
    echo "env.CUTILS_PATH not set!" >&2
    exit 1
fi

if [ "$CWORK_PATH" == "" ]; then
    CWORK_PATH=`echo ~`/cwork
fi

if [ "$Package" != "" ]; then
    cd $CWORK_PATH/$Package
fi

Deps=`cdep ensure`

if [ "$Dep" != "0" ]; then
    for pkg in $Deps; do
        Package=$pkg Dep=0 cmk $@
    done
fi

if [ ! -f "Makefile" -a ! -f "makefile" ]; then
    create_mk makefile $Target
fi

Import=$Deps make $@